version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the Flask server
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=true
      - FLASK_ENV=development
      - FLASK_DEBUG=1
